version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
        - public

  php-fpm:
      image: php:8-fpm
      volumes:
        - .:/var/www/html
      depends_on:
        - db
      networks:
        - public

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf:/etc/mysql/conf.d
    ports:
      - 3306:3306
    tty: true
    networks:
      - public

networks:
    public:
        driver: bridge